### ISSUE TITLE
9600K UHD630 开机黑屏30秒 测试了很多还是无法解决！

### ISSUE THREAD

**Issue by tnwss** [taina0407/Prime-Z390m-Plus-OpenCore-Hackintosh#2]

**Comment by taina0407** [comment]
Hello, for specific CPU and iGPU, please follow https://dortania.github.io/OpenCore-Install-Guide/config.plist/kaby-lake.html#deviceproperties guide to select correct platform-id and follow WhatEverGreen guide to patch framebuffer
